### ISSUE TITLE
site went blank?

### ISSUE THREAD

**Issue by Jacopo** [bahamas10/node-sshp#8]
Hello Dave, just wanted to notify you that right now:

http://sshp.daveeddy.com -> empty
https://sshp.daveeddy.com -> wrong cert (daveeddy.com)

**Comment by bahamas10** [comment]
Yes, unfortunately this was modified as a result of some recent (months ago) DNS changes - I removed all references to the site from this GitHub repo.

I'm going to attempt to make `sshp.daveeddy.com` just redirect to this github.

Thanks for noticing!

**Comment by bahamas10** [comment]
301 redirect added for `sshp.daveddy.com` -> `github.com/bahamas10/node-sshp`

thanks again!
