### ISSUE TITLE
Hey, you are the best!

### ISSUE THREAD

**Issue by beejei** [bahamas10/node-sshp#9]
This is the exact way I want to have.
This kind of interface is really needed for physical-machine maintainers.
I would like to build a simple web page which send out same command to thousand of servers, and showing the report by aggregating them all.
This is a real unix-like way.

**Comment by beejei** [comment]
What the, Now I can check all the disk space by just one command.
And can perform select or reduce from its result!

**Comment by bahamas10** [comment]
Thank you!! I'm glad you enjoy this software :D
